### ISSUE TITLE
Help by installation

### ISSUE THREAD

**Issue by mariusgrams** [futmkt/fut-api#1]
I downloaded the repository and created this php file:

`<?php
use FUTApi\Core;
use FUTApi\FutError;
try {
    $fut = new Core('email', 'password', 'platform', 'backup_code');
} catch(FutError $e) {
    $error = $e->GetOptions();
    die("We have an error logging in: ".$error['reason']);
}
$login = $fut->login();

?>`

I get following error:
Fatal error: Uncaught Error: Class 'FUTApi\Core' not found in C:\xampp\htdocs\Fut20Api\login.php:5 Stack trace: #0 {main} thrown in C:\xampp\htdocs\Fut20Api\login.php on line 5

Can anyone help me please by getting access to webapp?

**Comment by mynameisvasco** [comment]
You need to use composer

**Comment by martinop** [comment]
" Please set env('DS_PATH') before use the script." what should be that value? @mynameisvasco

**Comment by Helda90** [comment]
Value is path to DS.js. To directory, not file. 

DS_PATH = /path/to/directory # where is located file.

**Comment by martinop** [comment]
But now I got:

`Fatal error: Uncaught InvalidArgumentException: Header value must be scalar or null but GuzzleHttp\Psr7\Uri provided. in /Users/martin/Documents/Dev/simple-php-boilerplate/vendor/guzzlehttp/psr7/src/MessageTrait.php:190 Stack trace: #0 [internal function]: GuzzleHttp\Psr7\Request->GuzzleHttp\Psr7\{closure}(Object(GuzzleHttp\Psr7\Uri)) #1 /Users/martin/Documents/Dev/simple-php-boilerplate/vendor/guzzlehttp/psr7/src/MessageTrait.php(197): array_map(Object(Closure), Array) #2 /Users/martin/Documents/Dev/simple-php-boilerplate/vendor/guzzlehttp/psr7/src/MessageTrait.php(162): GuzzleHttp\Psr7\Request->trimHeaderValues(Array) #3 /Users/martin/Documents/Dev/simple-php-boilerplate/vendor/guzzlehttp/psr7/src/MessageTrait.php(147): GuzzleHttp\Psr7\Request->normalizeHeaderValue(Object(GuzzleHttp\Psr7\Uri)) #4 /Users/martin/Documents/Dev/simple-php-boilerplate/vendor/guzzlehttp/psr7/src/Request.php(46): GuzzleHttp\Psr7\Request->setHeaders(Array) #5 /Users/martin/Documents/Dev/simple-php-boilerplate/vendor/guzzlehttp/guzzle/src/Client in /Users/martin/Documents/Dev/simple-php-boilerplate/vendor/guzzlehttp/psr7/src/MessageTrait.php on line 190`

**Comment by martinop** [comment]
I think the login is not working for me

**Comment by Helda90** [comment]
Use dev-master. Error is fixed. But not released.
